import { SESClient, SendEmailCommand } from '@aws-sdk/client-ses'

const sesClient = new SESClient({
  region: process.env.AWS_REGION || 'ap-south-1',
})

const FROM_EMAIL = process.env.FROM_EMAIL || 'noreply@yourdomain.com'
const TO_EMAIL = process.env.TO_EMAIL || 'your-email@example.com'

export interface LeadData {
  inquiryType: 'ca' | 'salon'
  callerName?: string
  callerPhone: string
  inquiryDetails: string
  conversationSummary: string
  requirements?: string
  leadScore?: number
  timestamp: string
  callDuration?: number
}

/**
 * Send lead email using AWS SES
 */
export const sendLeadEmail = async (lead: LeadData): Promise<void> => {
  try {
    const subject = `New Lead: ${lead.inquiryType === 'ca' ? 'Chartered Accountancy' : 'Salon Appointment'} Inquiry`
    
    const emailBody = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background-color: #3b82f6; color: white; padding: 20px; border-radius: 5px 5px 0 0; }
    .content { background-color: #f9fafb; padding: 20px; border: 1px solid #e5e7eb; }
    .section { margin-bottom: 20px; }
    .label { font-weight: bold; color: #1f2937; }
    .value { color: #4b5563; margin-top: 5px; }
    .footer { margin-top: 20px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h2>🎯 New Lead Generated</h2>
    </div>
    <div class="content">
      <div class="section">
        <div class="label">Inquiry Type:</div>
        <div class="value">${lead.inquiryType === 'ca' ? 'Chartered Accountancy Services' : 'Salon Appointment'}</div>
      </div>
      
      ${lead.callerName ? `
      <div class="section">
        <div class="label">Name:</div>
        <div class="value">${lead.callerName}</div>
      </div>
      ` : ''}
      
      <div class="section">
        <div class="label">Phone Number:</div>
        <div class="value">${lead.callerPhone}</div>
      </div>
      
      <div class="section">
        <div class="label">Inquiry Details:</div>
        <div class="value">${lead.inquiryDetails}</div>
      </div>
      
      ${lead.requirements ? `
      <div class="section">
        <div class="label">Requirements:</div>
        <div class="value">${lead.requirements}</div>
      </div>
      ` : ''}
      
      <div class="section">
        <div class="label">Conversation Summary:</div>
        <div class="value">${lead.conversationSummary}</div>
      </div>
      
      ${lead.leadScore ? `
      <div class="section">
        <div class="label">Lead Score:</div>
        <div class="value">${lead.leadScore}/10</div>
      </div>
      ` : ''}
      
      ${lead.callDuration ? `
      <div class="section">
        <div class="label">Call Duration:</div>
        <div class="value">${lead.callDuration} seconds</div>
      </div>
      ` : ''}
      
      <div class="section">
        <div class="label">Timestamp:</div>
        <div class="value">${new Date(lead.timestamp).toLocaleString()}</div>
      </div>
    </div>
    <div class="footer">
      <p>This lead was automatically generated by the AI Voice Agent system.</p>
    </div>
  </div>
</body>
</html>
    `

    const command = new SendEmailCommand({
      Source: FROM_EMAIL,
      Destination: {
        ToAddresses: [TO_EMAIL],
      },
      Message: {
        Subject: {
          Data: subject,
          Charset: 'UTF-8',
        },
        Body: {
          Html: {
            Data: emailBody,
            Charset: 'UTF-8',
          },
          Text: {
            Data: `
New Lead Generated

Inquiry Type: ${lead.inquiryType === 'ca' ? 'Chartered Accountancy Services' : 'Salon Appointment'}
${lead.callerName ? `Name: ${lead.callerName}` : ''}
Phone: ${lead.callerPhone}
Inquiry: ${lead.inquiryDetails}
${lead.requirements ? `Requirements: ${lead.requirements}` : ''}
Summary: ${lead.conversationSummary}
${lead.leadScore ? `Lead Score: ${lead.leadScore}/10` : ''}
${lead.callDuration ? `Call Duration: ${lead.callDuration}s` : ''}
Timestamp: ${new Date(lead.timestamp).toLocaleString()}
            `.trim(),
            Charset: 'UTF-8',
          },
        },
      },
    })

    await sesClient.send(command)
    console.log('Lead email sent successfully')
  } catch (error: any) {
    console.error('Error sending lead email:', error)
    throw new Error(`Failed to send lead email: ${error.message}`)
  }
}

export const emailService = {
  sendLeadEmail,
}

